language: ruby
rvm:
  - 2.2.6

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get install postgresql-9.4-prefix postgresql-9.4-pgq3
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.4

before_script:
  - cp config/database.example.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:structure:load db:migrate
  - RAILS_ENV=test bundle exec rake db:second_base:create db:second_base:structure:load db:second_base:migrate
  - RAILS_ENV=test bundle exec rake db:seed

script:
  - bundle exec rspec
